<?php

namespace Lysice\XlsWriter\Supports\Chart;

class NoneChart extends Chart implements ChartInterface
{
    public function draw(array $data): Chart
    {
        parent::draw(); // TODO: Change the autogenerated stub
    }
}
